# Generated by Django 4.2.2 on 2023-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionauth', '0003_remove_useraccount_name_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_active',
            field=models.BooleanField(default=False),
        ),
    ]
