# Generated by Django 4.2.2 on 2023-08-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionauth', '0004_useraccount_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordToBeVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
