# Generated by Django 4.2.2 on 2023-08-01 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionauth', '0005_passwordtobeverified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordtobeverified',
            name='id',
        ),
        migrations.AddField(
            model_name='passwordtobeverified',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
